version: '3.9'
services:
  server:
    container_name: nestjs_server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env.dev
    networks:
      - mongo-compose-network
    depends_on:
      - mongo


  mongo:
    container_name: mongodb
    image: mongo:${MONGODB_VERSION}
    ports:
      - "${MONGODB_ROOT_PORT}:${MONGODB_ROOT_PORT}"
    networks:
      - mongo-compose-network
    volumes:
      - mongo-db:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGODB_ROOT_DATABASE}

networks:
  mongo-compose-network:
    driver: bridge

volumes:
  mongo-db:
