version: '3.9'
services:
  server:
    container_name: nestjs_server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
        - "${PORT}:${PORT}"
    env_file:
      - .env
    networks:
      - mongo-compose-network
    depends_on:
      - mongodb


  mongodb:
    container_name: mongodb
    image: mongo:${MONGODB_VERSION}
    ports:
      - "${MONGODB_HOST_PORT}:27017"
    networks:
      - mongo-compose-network
    volumes:
      - mongo-db:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_ROOT_PASSWORD}
      - MONGODB_DATABASE=${MONGODB_DATABASE}

networks:
  mongo-compose-network:
    driver: bridge

volumes:
  mongo-db:
